apiVersion: v1
kind: Service
metadata:
  name: notes-svc
spec:
  selector:
    app: notes
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  labels:
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "notes"
    tags.datadoghq.com/version: "0.1.0"
spec:
  selector:
    matchLabels:
      app: notes
  replicas: 1
  template:
    metadata:
      labels:
        app: notes
        tags.datadoghq.com/env: "prod" # Unified service tag - Pod Env tag
        tags.datadoghq.com/service: "notes" # Unified service tag - Pod Service tag
        tags.datadoghq.com/version: "0.1.0" # Unified service tag - Pod Version tag
        admission.datadoghq.com/enabled: "true" # Enable Admission Controller to mutate new pods part of this deployment
      annotations:
        ad.datadoghq.com/notes-app.logs: '[{"source":"python", "service":"notes", "tags":["foo:bar"]}]'
        admission.datadoghq.com/python-lib.version: "2.20.1"
    spec:
      containers:
      - name: notes-app
        image: notes-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: CALENDAR_HOST
            value: calendar
          - name: DB_HOST
            value: postgres
          - name: DD_AGENT_HOST  # TODO: is this needed?
            value: datadog
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_IAST_ENABLED
            value: "true"
          - name: DD_APPSEC_SCA_ENABLED
            value: "true"
