apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: docker-desktop
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    admissionController:
      enabled: true
      mutateUnlabelled: false
    apm:
      instrumentation:
        enabled: true
        enabledNamespaces:
        - default
        libVersions:
          java: "1.39.1"
          dotnet: "3.3.1"
          python: "2.11.7"
          js: "5.23.1"
          ruby: "2"
    logCollection:
      enabled: true
      containerCollectAll: true
    remoteConfiguration:
      enabled: true
    liveProcessCollection:
      enabled: true
    # TODO: security features?
    # cws:
    #   enabled: true
  